version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf

  php:
    build: .
    volumes:
      - ./:/code

  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root # ⬅︎ 🚨
      MYSQL_DATABASE: appdb
      MYSQL_USER: user # ⬅︎ 🚨
      MYSQL_PASSWORD: password # ⬅︎ 🚨
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root # ⬅︎ 🚨
    ports:
      - "8081:80"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP port for sending emails
      - "8025:8025"  # Web UI port to view emails

volumes:
  data:
