<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxS17Vl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxS17Vl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxS17Vl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxS17Vl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxS17Vl\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxS17Vl',
    'container.build_id' => '2eb6aa04',
    'container.build_time' => 1732301002,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxS17Vl');
