<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL8qAemA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL8qAemA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL8qAemA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL8qAemA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL8qAemA\App_KernelDevDebugContainer([
    'container.build_hash' => 'L8qAemA',
    'container.build_id' => '0943b481',
    'container.build_time' => 1734603814,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL8qAemA');
